module.exports = {
  SCREEN_ROUTER: {
    MAIN: "MAIN",
    AUTH: "AUTH"
  },
  SCREEN_ROUTER_AUTH: {
    LOGIN: "LOGIN",
    FORGOT_PASS: "FORGOT_PASS",
    REGISTER: "REGISTER"
  },
  SCREEN_ROUTER_APP: {
    HOME: "HOME",
    USER: "USER",
    HOME_DETAIL: "HOME_DETAIL",
    USER_DETAIL: "USER_DETAIL"
  },
  AUTH_LOADING: "AUTH_LOADING",
  API_STATUS: {
    RE_LOGIN: 403
  }
};
